/**
 * One-time script: upload homepage images from snacqo_frontend/public to Cloudinary
 * and write frontend src/config/homepage-images.ts with the resulting URLs.
 *
 * Run from snacqo_backend: npx tsx scripts/upload-homepage-images.ts
 *
 * Requires:
 * - CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET in .env
 * - Image files present in snacqo_frontend/public (and public/Flavors/)
 */
import 'dotenv/config';
import * as fs from 'fs';
import * as path from 'path';
import { uploadImage } from '../src/services/cloudinary.js';

// Run from snacqo_backend; parent is repo root (snacqo_app)
const ROOT = path.resolve(process.cwd(), '..');
const PUBLIC_DIR = path.join(ROOT, 'snacqo_frontend', 'public');
const FRONTEND_CONFIG_PATH = path.join(ROOT, 'snacqo_frontend', 'src', 'config', 'homepage-images.ts');

const HOMEPAGE_IMAGES = [
  { key: 'heroAlmonds', relativePath: 'cashews&almonds.png', publicId: 'cashews-almonds' },
  { key: 'vibeCheck', relativePath: 'Vibecheckk.png', publicId: 'vibecheck' },
  { key: 'vib', relativePath: 'vib.png', publicId: 'vib' },
  { key: 'flavors.darkchocolatealmonds', relativePath: 'Flavors/darkchocolatealmonds.png', publicId: 'flavors-darkchocolatealmonds' },
  { key: 'flavors.doublechocomochaalmonds', relativePath: 'Flavors/doublechocomochaalmonds.png', publicId: 'flavors-doublechocomochaalmonds' },
  { key: 'flavors.kesarkulficashews', relativePath: 'Flavors/kesarkulficashews.png', publicId: 'flavors-kesarkulficashews' },
  { key: 'flavors.strawberrycashews', relativePath: 'Flavors/strawberrycashews.png', publicId: 'flavors-strawberrycashews' },
  { key: 'flavors.pizzacashews', relativePath: 'Flavors/pizzacashews.png', publicId: 'flavors-pizzacashews' },
  { key: 'flavors.chocolatealmonds', relativePath: 'Flavors/chocolatealmonds.png', publicId: 'flavors-chocolatealmonds' },
] as const;

async function main() {
  console.log('Uploading homepage images to Cloudinary (folder: snacqo/homepage)...\n');

  const results: Record<string, string> = {};
  const flavors: Record<string, string> = {};

  for (const { key, relativePath, publicId } of HOMEPAGE_IMAGES) {
    const filePath = path.join(PUBLIC_DIR, relativePath);
    if (!fs.existsSync(filePath)) {
      throw new Error(`Missing image: ${filePath}\nAdd the file and run again.`);
    }
    const buffer = fs.readFileSync(filePath);
    const { url } = await uploadImage(buffer, {
      folder: 'snacqo/homepage',
      publicId,
    });
    console.log(`  ✓ ${relativePath} → ${url}`);
    if (key.startsWith('flavors.')) {
      flavors[key.replace('flavors.', '')] = url;
    } else {
      results[key] = url;
    }
  }

  const tsContent = `/**
 * Homepage image URLs (Cloudinary). Generated by snacqo_backend/scripts/upload-homepage-images.ts
 * Do not edit by hand; re-run the script to refresh URLs.
 */

export const homepageImages = {
  heroAlmonds: "${results.heroAlmonds}",
  vibeCheck: "${results.vibeCheck}",
  vib: "${results.vib}",
  flavors: {
    darkchocolatealmonds: "${flavors.darkchocolatealmonds}",
    doublechocomochaalmonds: "${flavors.doublechocomochaalmonds}",
    kesarkulficashews: "${flavors.kesarkulficashews}",
    strawberrycashews: "${flavors.strawberrycashews}",
    pizzacashews: "${flavors.pizzacashews}",
    chocolatealmonds: "${flavors.chocolatealmonds}",
  },
} as const;

export type HomepageImages = typeof homepageImages;
`;

  const configDir = path.dirname(FRONTEND_CONFIG_PATH);
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }
  fs.writeFileSync(FRONTEND_CONFIG_PATH, tsContent, 'utf-8');
  console.log(`\nWrote ${FRONTEND_CONFIG_PATH}`);
  console.log('Done. Update Hero, VibeCheck, and Flavors to use homepageImages from this config.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
