/**
 * Homepage image URLs (Cloudinary). Generated by snacqo_backend/scripts/upload-homepage-images.ts
 * Do not edit by hand; re-run the script to refresh URLs.
 */

export const homepageImages = {
  heroAlmonds: "https://res.cloudinary.com/dijweaxpb/image/upload/v1772414466/snacqo/homepage/cashews-almonds.png",
  vibeCheck: "https://res.cloudinary.com/dijweaxpb/image/upload/v1772414468/snacqo/homepage/vibecheck.png",
  vib: "https://res.cloudinary.com/dijweaxpb/image/upload/v1772414469/snacqo/homepage/vib.png",
  flavors: {
    darkchocolatealmonds: "https://res.cloudinary.com/dijweaxpb/image/upload/v1772414471/snacqo/homepage/flavors-darkchocolatealmonds.png",
    doublechocomochaalmonds: "https://res.cloudinary.com/dijweaxpb/image/upload/v1772414473/snacqo/homepage/flavors-doublechocomochaalmonds.png",
    kesarkulficashews: "https://res.cloudinary.com/dijweaxpb/image/upload/v1772414475/snacqo/homepage/flavors-kesarkulficashews.png",
    strawberrycashews: "https://res.cloudinary.com/dijweaxpb/image/upload/v1772414477/snacqo/homepage/flavors-strawberrycashews.png",
    pizzacashews: "https://res.cloudinary.com/dijweaxpb/image/upload/v1772414479/snacqo/homepage/flavors-pizzacashews.png",
    chocolatealmonds: "https://res.cloudinary.com/dijweaxpb/image/upload/v1772414482/snacqo/homepage/flavors-chocolatealmonds.png",
  },
} as const;

export type HomepageImages = typeof homepageImages;
